import { DragPanel } from "../DragPanel.jsx";
import { simDaysToDate } from "../../utils/timeUtils.js";
import { mobileSheet, bClose } from "../../styles/panelStyles.js";

export default function BookmarkPanel({visible,dispatchPanel,bookmarks,bookmarkName,setBookmarkName,saveBM,delBM,importState,S,isPhone,lang,pn,bF,bN}){
  if(!visible)return null;
  var en=lang==="en";
  return <DragPanel style={Object.assign({},pn,{top:80,left:10,width:220,maxWidth:"calc(100vw - 20px)",padding:"10px 12px"},mobileSheet(isPhone))}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:11,fontWeight:"bold",color:"rgba(255,220,120,0.95)"}}>{en?"🔖 Bookmarks":"🔖 ブックマーク"}</span><button aria-label={en?"Close":"閉じる"} style={bClose} onClick={function(){dispatchPanel({type:"SET",key:"bookOpen",value:false});}}>✕</button></div><div style={{display:"flex",gap:3,marginBottom:6}}><input aria-label={en?"Bookmark name":"ブックマーク名"} type="text" placeholder={en?"Name...":"名前..."} value={bookmarkName} onChange={function(e){setBookmarkName(e.target.value);}} style={{flex:1,background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.2)",borderRadius:3,color:"rgba(255,255,255,0.9)",fontSize:9,padding:"3px 5px",outline:"none",fontFamily:"system-ui"}}/><button style={bN} onClick={function(){saveBM(bookmarkName||simDaysToDate(S.current.t));setBookmarkName("");}}>{en?"Save":"保存"}</button></div><div style={{maxHeight:180,overflowY:"auto"}}>{bookmarks.length===0&&<div style={{fontSize:9,color:"rgba(255,255,255,0.3)",padding:"4px 0"}}>{en?"No bookmarks":"保存されたブックマークなし"}</div>}{bookmarks.map(function(bm,bi){return <div key={bi} style={{display:"flex",alignItems:"center",gap:3,padding:"2px 0",borderBottom:"1px solid rgba(255,255,255,0.06)"}}><button style={Object.assign({},bF,{flex:1,textAlign:"left",fontSize:9,padding:"3px 5px",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"})} onClick={function(){importState(bm.code);dispatchPanel({type:"SET",key:"bookOpen",value:false});}}>{bm.name}</button><button style={Object.assign({},bF,{padding:"2px 5px",fontSize:8,color:"rgba(255,100,100,0.7)",flexShrink:0})} onClick={function(){delBM(bi);}}>✕</button></div>;})}</div></DragPanel>;
}
