import { DragPanel } from "../DragPanel.jsx";
import { computeNightSky } from "../../utils/computations.js";
import { mobileSheet } from "../../styles/panelStyles.js";

export default function NightSkyPanel({visible,dispatchPanel,nightSkyLat,setNightSkyLat,nightSkyLng,setNightSkyLng,S,isPhone,lang,pn,bF}){
  if(!visible)return null;
  var en=lang==="en";
  return <DragPanel style={Object.assign({},pn,{top:80,left:isPhone?10:240,width:230,maxWidth:"calc(100vw - 20px)",padding:"10px 12px"},mobileSheet(isPhone))}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:11,fontWeight:"bold",color:"rgba(255,220,80,0.95)"}}>{en?"🌙 Tonight's Sky":"🌙 今夜の空"}</span><button aria-label={en?"Close":"閉じる"} style={Object.assign({},bF,{padding:"2px 6px",fontSize:9})} onClick={function(){dispatchPanel({type:"SET",key:"nightSkyOpen",value:false});}}>✕</button></div><div style={{display:"flex",gap:4,alignItems:"center",marginBottom:6,flexWrap:"wrap"}}><span style={{fontSize:9,color:"rgba(255,255,255,0.45)"}}>{en?"Lat":"緯度"}</span><input aria-label={en?"Latitude":"緯度"} type="number" min="-90" max="90" value={nightSkyLat} onChange={function(e){setNightSkyLat(+e.target.value);}} style={{width:44,background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.18)",borderRadius:3,color:"rgba(255,255,255,0.9)",fontSize:9,padding:"2px 4px",outline:"none",fontFamily:"system-ui"}}/><span style={{fontSize:9,color:"rgba(255,255,255,0.45)"}}>° {en?"Lng":"経度"}</span><input aria-label={en?"Longitude":"経度"} type="number" min="-180" max="180" value={nightSkyLng} onChange={function(e){setNightSkyLng(+e.target.value);}} style={{width:44,background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.18)",borderRadius:3,color:"rgba(255,255,255,0.9)",fontSize:9,padding:"2px 4px",outline:"none",fontFamily:"system-ui"}}/><button aria-label={en?"Use current location":"現在地を取得"} style={Object.assign({},bF,{fontSize:8,padding:"2px 5px"})} onClick={function(){if(navigator.geolocation)navigator.geolocation.getCurrentPosition(function(pos){setNightSkyLat(Math.round(pos.coords.latitude));setNightSkyLng(Math.round(pos.coords.longitude));},function(){});}}>📍</button></div>{(function(){var nsd=computeNightSky(S.current.t,nightSkyLat,nightSkyLng);return <div><div style={{fontSize:9,color:nsd.isNight?"rgba(100,180,255,0.85)":"rgba(255,200,80,0.8)",marginBottom:5}}>{nsd.isNight?(en?"🌙 Good for night observation":"🌙 夜間観測適"):(en?"☀ Daytime (Sun "+nsd.sunAlt+"°)":"☀ 昼間 (太陽 "+nsd.sunAlt+"°)")}</div>{nsd.items.filter(function(x){return x.name!=="地球";}).map(function(item){return <div key={item.name} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"2px 0",borderBottom:"1px solid rgba(255,255,255,0.05)",opacity:item.vis?1:0.38}}><span style={{fontSize:9,color:"rgba(255,255,255,0.88)"}}>{item.vis?"✓ ":""}{item.name}</span><span style={{fontSize:8,color:"rgba(180,200,255,0.6)"}}>{item.alt}° / {item.mag}{en?" mag":"等"}</span></div>;})}</div>;}())}</DragPanel>;
}
